name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: checkout
      run: git clone --recursive https://github.com/uNetworking/uWebSockets.py.git
    - name: build
      run: make -C uWebSockets.py
